### PR TITLE
fix: Vendor rust dependencies (#1722)

### PR DESCRIPTION
**Pull request by abhishek818**
Vendor deps with git revisions, enabling offline builds.

Also tested with `cargo build --offline`

fixes: #1722 
/claim #1722 

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [X] I have performed a self-review of my code.
- [X] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

## Summary by CodeRabbit

- **New Features**
  - Introduced Apollo tracing extensions for `async_graphql`, enabling trace and metric reporting to Apollo Studio.
  - Added functionality to verify Apache htpasswd files with support for multiple encryption algorithms.

- **Documentation**
  - Provided templates for pull requests and dependabot configuration to enhance project maintainability.

- **Bug Fixes**
  - Updated dependencies and fixed issues in the Apollo tracing extensions as documented in the CHANGELOG.

- **Refactor**
  - Enhanced code for handling protobuf files and introduced new modules for JSON serialization and system information retrieval.

- **Style**
  - Configured Rust code formatting settings for the htpasswd-verify package.

### CODE REVIEW

**Comment by abhishek818** [comment]
@tusharmath  Up for review.

**Comment by amitksingh1490** [comment]
@abhishek818 It should work offline if you have dependencies already installed locally.
You don't need to package all the dependencies inside Tailcall

**Comment by abhishek818** [comment]
@amitksingh1490 alright, then I guess packaging deps with git revisions should be enough, Pls suggest if i am missing something here. Will revert back to my 1st commit.

**Comment by amitksingh1490** [comment]
@abhishek818  we don't want to duplicate the code of the any dependency because it will be very hard to maintain.

**Pull request closed without merging**
