### PR TITLE
fix: dedupe dedupe settings

### LINKED ISSUE #2182: Restructure dedupe settings
At present, we have three configurations:

```rust
// mod config::server
struct Server {
  batch_execution: Option<bool>
}

// mod config::upstream
struct Upstream {
  dedupe: Option<bool>,
  dedupe_in_flight: Option<bool>
}
```

We need to merge these configurations into a single one:

```rust
// mod config::server
struct Server {
  dedupe: Option<bool>
}
```

When this new `dedupe` configuration is enabled, it should automatically enable all the features that were previously dependent on the `dedupe_in_flight` and `batch_execution` flags.

**Note:** Update documentation with the new settings.

### PR DESCRIPTION
**Pull request by bnchi**
**Summary:**  
- Removes batch_execution field from Server config, dedupe_in_flight and dedupe fields from Upstream.
- Adds dedupe to Server config 
- Refactor request_handler.rs and io.rs to use the new dedupe defined in Server config  

**Issue Reference(s):**  
Fixes #2182

**Build & Testing:**

- [X] I ran `cargo test` successfully.
- [X] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [X] I have added relevant unit & integration tests.
- [X] I have updated the [documentation] accordingly.
- [X] I have performed a self-review of my code.
- [X] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

**Review by tusharmath — APPROVED** [review]

**Comment by bnchi** [comment]
Thanks for fixing the lint issues, I didn't expect the warning will cause the lint to fail in CI.

One more thing I wanted to quickly get your opinion on this line 
https://github.com/tailcallhq/tailcall/blob/4890980cd7589c4b7476e35417d1364d2ed2788b/src/core/ir/io.rs#L74

The above if - else block is probably not needed because this block will get executed only if this check here failed  
https://github.com/tailcallhq/tailcall/pull/2183/files#diff-c682c5a9b03602a6b44f7f216b74e65018221f460a79b6b59e72905dfd98b9c6R69

so I guess we can get rid of the if completely right ? 

@tusharmath

**Comment by tusharmath** [comment]
That would be right.

**Comment by bnchi** [comment]
I made a commit that fixes the unnecessary check thanks.

**Comment by tusharmath** [comment]
@bnchi Can you please update the documentation for these changes here - https://github.com/tailcallhq/tailcallhq.github.io

**Pull request merged**
