### PR TITLE
feat: Linter for schema

### LINKED ISSUE #1322: Validate schema using linters
Tailcall should ensure consistency in building the final GraphQL schema. This is the standard it should follow:

**Case styles**
- Field names should use `camelCase`. 
- Type names should use `PascalCase`.
- Enum names should use `PascalCase`.
- Enum values should use `ALL_CAPS`, because they are similar to constants.

There are two approaches to solve this problem:
1. When the setting is enabled, we can throw a validation error that the developer see and fix using the `@modify` operator.
2. We can automatically fix it for the user.

**Proposal**
```graphql
schema @server(lint: {field: true, type: true, enum: true, enumValue: true, autoFix: false}) {
  query: Query
}
```

**Technical Requirements**
Use the `ConfigOptimizer` API defined over here https://github.com/tailcallhq/tailcall/issues/1653

### PR DESCRIPTION
**Pull request by webbdays**
**Summary:**  
Linter

**Issue Reference(s):**  
may be Fixes #1322

**Build & Testing:**

- [Yes] I ran `cargo test` successfully.
- [fixed] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [yes I have performed a self-review of my code.
- [yes] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

**Comment by tusharmath** [comment]
Moving it to draft, until we have tests to prove that this works. Current implementation doesn't seem to be working. Feel free to change it back once you have tests and it's ready for review.

**Comment by webbdays** [comment]
ok.

**Comment by webbdays** [comment]
I don't know why the tracing arguments are showing not covered. weird.
@tusharmath
Any idea of this.

**Comment by webbdays** [comment]
Written tests working fine.

**Comment by webbdays** [comment]
Still
Have few problems that need to be taken care.
Getting some validation errors when we want to lint field to Pascal, type to camel like these.
But working fine with
field : Camel, type: Pascal

Another thing is still need work to change fields in args. {{value.id}}.

still these need to be addressed.

**Comment by webbdays** [comment]
Hello and hi @coderabbitai,
any idea why code coverage is not shown/covered for this tracing.

**Comment by webbdays** [comment]
action taken 🤒

**Comment by webbdays** [comment]
@meskill 
i have a problem in this.
Its very difficult to aauto lint.

**Comment by meskill** [comment]
> @meskill i have a problem in this. Its very difficult to auto lint using config struct data. Can we opt for a cli solution which lint even before the schema is read by the config reader? i think its best.

could you elaborate more on your suggestion how to solve it in terms how it will work and how it'll solve issues you're facing?

**Pull request closed without merging**
