### PR TITLE
test: run execution spec parallel

### LINKED ISSUE #1461: execution spec bails out on the first failure
Currently execution_spec runs each test one by one and fails on the first error. The expectation is to run the tests in parallel and show all the failures at once.

### PR DESCRIPTION
**Pull request by Bhavyajain21**
/claim #1461 
/fixes #1461 

**Implementation includes :**

- optimal process of reading multiple files concurrently using Tokio's asynchronous task handling
- running the tests in parallel and show all the failures at once.

## Summary by CodeRabbit

- **Tests**
	- Improved test efficiency and error reporting by introducing parallel task execution.

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
Please review @tusharmath

**Comment by tusharmath** [comment]
@Bhavyajain21 This is a duplicate of https://github.com/tailcallhq/tailcall/pull/1462
by @mehulmathur16 
One of you should close your PR and work on something else.

**Comment by Bhavyajain21** [comment]
This includes optimized process of reading multiple files concurrently using Tokio's asynchronous task handling.

**Comment by tusharmath** [comment]
What's the improvement in execution time when compared to main?

**Comment by Bhavyajain21** [comment]
> What's the improvement in execution time when compared to main?

@tusharmath Asynchronous handling using Tokio allows for overlapping I/O operations, which can result in significant performance improvements when dealing with I/O-bound tasks, such as reading files from disk. By initiating multiple file read operations concurrently and efficiently handling the results as they become available, asynchronous tasks can make better use of system resources and reduce overall execution time.

**Comment by tusharmath** [comment]
Can you share exact numbers.

**Comment by Bhavyajain21** [comment]
@tusharmath To provide exact numbers on efficiency improvement, I plan to measure the execution time of the test suite both sequentially and with the parallel implementation. I'll use Instant::now() from std::time to capture the start and end times.

I'll update the PR with the exact numbers and performance improvement percentage once I've completed the measurements.

**Comment by Bhavyajain21** [comment]
@tusharmath Here's the screenshot attached with exact numbers and performance improvement percentage after completing the measurements.

**Comment by tusharmath** [comment]
That's pretty low.

**Comment by Bhavyajain21** [comment]
> That's pretty low.

And this is the one after running it with my logic of code to optimize reading multiple files concurrently using Tokio's asynchronous task handling. It is increased to 10%

Screenshot 2024-03-17 at 5 18 47 PM

**Comment by tusharmath** [comment]
Using multi threading we should have achived order of magnitude of increase in performance. It seems like we are still running the tests sequentially.

**Comment by Bhavyajain21** [comment]
> Using multi threading we should have achived order of magnitude of increase in performance. It seems like we are still running the tests sequentially.

@tusharmath You're right, multithreading should ideally lead to a much bigger performance improvement than the current 11%

Though I did a search about it and got to know that there could be a few of these reasons for this:

Shared Resources: The tests might be waiting on shared resources like databases or files, creating bottlenecks.

Thread Overhead: Managing threads can introduce overhead that negates the benefits for short-running tests.

Test Design: The tests might not be properly divided for parallel execution.


Using the code in the other PR, it is coming 9% as well.

**Comment by tusharmath** [comment]
This approach requires a lot more code to maintain. Opened up a new issue to track it https://github.com/tailcallhq/tailcall/issues/1500

/tip 20

**Comment by Bhavyajain21** [comment]
Thanks for the tip! @tusharmath

**Pull request closed without merging**
