### PR TITLE
refactor(2641): move snapshot tests for the gen command 

### LINKED ISSUE #2641: Move snapshot tests for the gen command
**Technical Requirements**

- Move the tests from `src/cli/generator/tests` to `tests/cli/gen.rs`
- Move fixtures also to the `tests` dir.
- Use `include_config!` macro to load the configurations.
- Ensure older tests/snapshots are deleted.
- No semantic change should happen in the tests during the migration.

related #2640

### PR DESCRIPTION
**Pull request by varshith257**
**Summary:**  

Requirements

- [x] Move the tests from `src/cli/generator/tests` to `tests/cli/gen.rs`
- [x] Move fixtures also to the tests dir.
- [x] Use `include_config! macro` to load the configurations.
- [x] Ensure older tests/snapshots are deleted.
- [x] No semantic change should happen in the tests during the migration

.
**Issue Reference(s):**  
Fixes #2641 
/claim #2641  

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [x] I have added relevant unit & integration tests.
- [x] I have updated the [documentation] accordingly.
- [x] I have performed a self-review of my code.
- [x] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

**Comment by varshith257** [comment]
@tusharmath   I have run ./lint.sh --mode=fix to fix all linting issues raised by ./lint.sh --mode=check and showing pass in my local but here failing

**Comment by tusharmath** [comment]
could be a version mismatch. Can you try upgrading your local rustfmt and try?

**Comment by tusharmath** [comment]
Moving to draft to reduce noise and improve CI efficiency. Once you are ready just mark it as "ready to review". Feel free to give a shoutout on the #contributors channel on Discord if you want immediate attention.

**Comment by varshith257** [comment]
Okay 👍

**Pull request closed without merging**
