### PR TITLE
design doc to add grpc support for tailcall added

### PR DESCRIPTION
**Pull request by deepakdinesh1123**
/claim #525

**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #... _(Replace "..." with the issue number)_

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the documentation accordingly (if applicable).
- [ ] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by deepakdinesh1123** [comment]
@tusharmath Could you please provide some feedback on this?

**Comment by Min2who** [comment]
Hi @tusharmath is this issue is closed or completed

**Comment by tusharmath** [comment]
@Min2who This is closed. I was trying out an experiment to take help from the community to write architecture specification documents. It's seems like it's harder to expect someone who hasn't spent enough time with us and has an understanding of our vision to write such specifications. 

For this particular issue we have https://github.com/tailcallhq/tailcall/issues/414 which is open for anyone to pick.

**Pull request closed without merging**
