### PR TITLE
Feature: lint feature for schema

### LINKED ISSUE #1322: Validate schema using linters
Tailcall should ensure consistency in building the final GraphQL schema. This is the standard it should follow:

**Case styles**
- Field names should use `camelCase`. 
- Type names should use `PascalCase`.
- Enum names should use `PascalCase`.
- Enum values should use `ALL_CAPS`, because they are similar to constants.

There are two approaches to solve this problem:
1. When the setting is enabled, we can throw a validation error that the developer see and fix using the `@modify` operator.
2. We can automatically fix it for the user.

**Proposal**
```graphql
schema @server(lint: {field: true, type: true, enum: true, enumValue: true, autoFix: false}) {
  query: Query
}
```

**Technical Requirements**
Use the `ConfigOptimizer` API defined over here https://github.com/tailcallhq/tailcall/issues/1653

### PR DESCRIPTION
**Pull request by webbdays**
**Summary:**  
_Added `linter_schema `module_
_It includes the lint code_
Used config Structure.

**Issue Reference(s):**  
Fixes #1322
/claim #1322

**Build & Testing:**

- [yes] I ran `cargo test` successfully.
- [yes] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [No] I have added relevant unit & integration tests. (Will add next)
- [No] I have updated the [documentation] accordingly. (Will update docs)
- [Yes] I have performed a self-review of my code.
- [Yes] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

**Comment by webbdays** [comment]
.

**Comment by tusharmath** [comment]
@webbdays Are you still on this? When can it be ready for review?

**Comment by webbdays** [comment]
Yes, I will resume it.
If it's not urgent can I make it by this Saturday or Sunday.

**Comment by webbdays** [comment]
changing the field, type usage is tricky here.
```javascript
"Query": Type { fields: {
                "posts": Field { type_of: "Post", list: true, required: false, list_type_required: false, args: {}, doc: None, modify: None, omit: None, http: Some(Http { base_url: None, body: None, encoding: ApplicationJson, group_by: [], headers: [], input: None, method: GET, path: "/posts", output: None, query: []
                    }), call: None, grpc: None, script: None, const_field: None, graphql: None, cache: None, protected: None
                },
                "user": Field { type_of: "user", list: false, required: false, list_type_required: false, args: {
                        "id": Arg { type_of: "Int", list: false, required: true, doc: None, modify: None, default_value: None
                        }
                    }, doc: None, modify: None, omit: None, http: Some(Http { base_url: None, body: None, encoding: ApplicationJson, group_by: [], headers: [], input: None, method: GET, path: "/users/{{args.id}}", output: None, query: []
                    }), call: None, grpc: None, script: None, const_field: None, graphql: None, cache: None, protected: None
                },
                "users": Field { type_of: "user", list: true, required: false, list_type_required: false, args: {}, doc: None, modify: None, omit: None, http: Some(Http { base_url: None, body: None, encoding: ApplicationJson, group_by: [], headers: [], input: None, method: GET, path: "/users", output: None, query: []
                    }), call: None, grpc: None, script: None, const_field: None, graphql: None, cache: None, protected: None
                }
            }, added_fields: [], doc: None, interface: false, implements: {}, variants: None, scalar: false, cache: None, protected: None, tag: None
        },
``` 
for
{{args.id}}
if id is Id
and we need to lint it to camel case.
and for type_of
Any idea of how to deal with these.

**Pull request closed without merging**
