### PR TITLE
fix: #347 Optimize impl PathString for EvaluationContext

### PR DESCRIPTION
**Pull request by Nirali-Ahir**
fix: #347 
/claim #347

I've removed the redundant result variable and the extra match statement, leading to more concise and readable code. I also used the map function to convert the obtained value to a Cow without an additional match statement.

### CODE REVIEW

**Comment by tusharmath** [comment]
@Nirali-Ahir we will need some benchmarks to assert if the performance has improved. We are using [criterion](https://docs.rs/criterion/latest/criterion/) for this.

**Comment by tusharmath** [comment]
@Nirali-Ahir Are you still working on this?

**Comment by Nirali-Ahir** [comment]
> @Nirali-Ahir Are you still working on this?

yes

**Comment by tusharmath** [comment]
Awesome! Looking forward to your PR.

**Comment by tusharmath** [comment]
Closing this PR for now @Nirali-Ahir Feel free to open it again incase you wish to continue on it further.

**Comment by Nirali-Ahir** [comment]
@tusharmath  i have already had Witten benchmarks, will test it and create new pr

**Comment by tusharmath** [comment]
@Nirali-Ahir We need to create a PR with optimizations. These optimizations should be backed by benchmarks, that's why need them. Just the benchmarks won't be enough unfortunately.

**Pull request closed without merging**
