### PR TITLE
refactor: re-write gen_gql_schema.rs

### PR DESCRIPTION
**Pull request by 0del**
**Summary:**  
- as title 

**Issue Reference(s):**  
Fixes https://github.com/tailcallhq/tailcall/issues/1510

**TODO**
- [x] Split the large file into smaller logical files
- [x] re-writer `writer` or `ServiceDocument` ,etc...
- [ ] test

### CODE REVIEW

**Comment by tusharmath** [comment]
@0del Looking forward to this PR :)

**Comment by 0del** [comment]
I was struggling to test this PR, perhaps i don't have more bandwidth to continue working on this issue 
i will close this PR, someone else can take over and work on this 
cc @tusharmath

**Comment by harshbisle** [comment]
> I was struggling to test this PR, perhaps i don't have more bandwidth to continue working on this issue 
> i will close this PR, someone else can take over and work on this 
> cc @tusharmath 

Hey @0del  would like to collaborate. How do I DM?

**Comment by 0del** [comment]
Screenshot 2024-04-08 at 22 14 26
i send a request to you @harshbisle

**Pull request closed without merging**
