### PR TITLE
fix(650): Upgrade hyper to 1.0

### LINKED ISSUE #650: Upgrade hyper to 1.0
Renovate has created the base PR which doesn't pass the CI checks.

https://github.com/tailcallhq/tailcall/pull/636

**Technical Requirements**
- Hyper version for both server should be updated to 1.0
- No performance degradation should be observed
- No tests should fail or require modification

### PR DESCRIPTION
**Pull request by giraffekey**
Fixes #650
/claim #650

### CODE REVIEW

**Comment by giraffekey** [comment]
Any update on whether this will be merged?

**Comment by amitksingh1490** [comment]
@giraffekey Please resolve conflicts and make the CI to pass.

**Comment by amitksingh1490** [comment]
Builds are failing moving this to draft

**Comment by giraffekey** [comment]
The tests are failing for me because snapshots in `tests/core` no longer match. It expects `Content-Type: application/json` in the headers but can't find it. Not sure how to fix this.

**Pull request closed without merging**
