### PR TITLE
refactor: Split tc.rs for each command

### LINKED ISSUE #2281: refactor: Split `tc.rs` for each command
Create a module with `tc/mod.rs` and for each command create a separate file. Common helpers can be in the same `tc` module. Expose a single async function from the `tc` module for public consumption.

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #2281
Summary:
Refactored tc.rs into separate command modules within tc directory.

Issue Reference(s):
Fixes #2281

Details:

Created individual module files (check.rs, gen.rs, helpers.rs, init.rs, start.rs) within the tc directory.
Moved corresponding command implementations into their respective files for better organization.
Updated tc/mod.rs to declare each module (check, gen, helpers, init, start).
Updated main.rs and other relevant files to import and use the tc module correctly.
Build & Testing:

 I ran cargo test successfully.
 I have run ./lint.sh --mode=fix to fix all linting issues raised by ./lint.sh --mode=check.

Here's a suggested PR description for your changes:

Summary:
Refactored tc.rs into separate command modules within tc directory.

Issue Reference(s):
Fixes #2281

Details:

Created individual module files (check.rs, gen.rs, helpers.rs, init.rs, start.rs) within the tc directory.
Moved corresponding command implementations into their respective files for better organization.
Updated tc/mod.rs to declare each module (check, gen, helpers, init, start).
Updated main.rs and other relevant files to import and use the tc module correctly.
Build & Testing:

 I ran cargo test successfully.
 I have run ./lint.sh --mode=fix to fix all linting issues raised by ./lint.sh --mode=check.
Checklist:

 I have performed a self-review of my code.

### CODE REVIEW

**Comment by beelchester** [comment]
Copy of #2286

**Comment by Anshgrover23** [comment]
no i have made my own

**Comment by tusharmath** [comment]
Closing in favour of https://github.com/tailcallhq/tailcall/pull/2286

**Comment by Anshgrover23** [comment]
but why i have made my mehnat

**Comment by Anshgrover23** [comment]
@tusharmath see there is errors in his prs

**Comment by tusharmath** [comment]
@Anshgrover23 https://tailcall.run/docs/contributors/bounty/

**Pull request closed without merging**
