### PR TITLE
fix(2665): ensure infer_type_names sent only once

### LINKED ISSUE #2665: Send system message only once in `infer_type_names`
Infer Type Names sends the system message everytime with user message. Fix it such that the system message is only sent once for all the types who's name needs to be inferred, and the user message is sent one time for each type whose name needs to be inferred.

### PR DESCRIPTION
**Pull request by harshtech123**
fix: Resolve issue described in #2665  /claim #2665

**Summary:**  
 This ensures that the system messages are sent only once, while the user message is sent for each type whose name needs to be inferred.

**Issue Reference(s):**  
Fixes #2665 

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [x] I have added relevant unit & integration tests.
- [x] I have updated the [documentation] accordingly.
- [x] I have performed a self-review of my code.
- [x] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

**Comment by tusharmath** [comment]
Thank you for your contribution to the project. Unfortunately, I am unable to merge this pull request as the changes proposed do not align with the current project requirements or standards. I encourage you to review our docs, contributing guidelines and look forward to more suitable contributions in the future. Thank you for your understanding.

**Comment by tusharmath** [comment]
Unnecessary files have been deleted. Please revert.

**Review by harshtech123 — COMMENTED** [review]
restored files

**Comment by tusharmath** [comment]
closing in favour of https://github.com/tailcallhq/tailcall/pull/2676

**Pull request closed without merging**
