### PR TITLE
feat: add @file directive

### LINKED ISSUE #932: feature: add a `@file` operator
Add a `@file` operator like `@http` to read data from a file.

```graphql
schema {
  query: Query
}

type Query {
  user: User @file(src: "./users.json")
}
```

**Technical Requirements:**
- The file should be read only once at the time of starting the server.
- Check should not validate if the file exists.
- File path should be relative to the config.
- File format should be detected via file extension.
- Support - YAML, JSON for now.

### PR DESCRIPTION
**Pull request by mogery**
**Summary:**  
Adds the `@file` directive, like described in #932. Uses `compile_const` under the hood for max code reuse and to make sure we only read a file once.

**Issue Reference(s):**  
Fixes #932 
/claim #932

Also partly addresses #764 

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [x] I have added relevant unit & integration tests.
- [x] I have updated the [documentation] accordingly.
   - tailcallhq/tailcallhq.github.io#100 
- [x] I have performed a self-review of my code.
- [x] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcall/tree/main/docs

### CODE REVIEW

**Comment by mogery** [comment]
This is ready now as well.

**Comment by mogery** [comment]
@meskill Do the codecov issues on this make sense? I think the testing is good enough. Not sure why the missed lines are missed.

**Comment by meskill** [comment]
> @meskill Do the codecov issues on this make sense? I think the testing is good enough. Not sure why the missed lines are missed.

They do. You can check the report or annotations in the pr. It mostly about some invalid cases check and usage of file inside `@expr`

**Comment by mogery** [comment]
> > @meskill Do the codecov issues on this make sense? I think the testing is good enough. Not sure why the missed lines are missed.
> 
> They do. You can check the report or annotations in the pr. It mostly about some invalid cases check and usage of file inside `@expr`

ohhhhh! thanks. i didn't even think about `@expr`

**Comment by mogery** [comment]
Alright, added tests for expr as well.

**Comment by mogery** [comment]
Closing this PR as reworking it to use `@link` and `@const` will cause the code to be much different. @tusharmath Could you assign me to #932 and #764 as well? The new PR will solve both issues.

**Pull request closed without merging**
