### PR TITLE
chore: fmt to capture Writer

### PR DESCRIPTION
**Pull request by ssddOnTop**
related to #2640

### CODE REVIEW

**Comment by tusharmath** [comment]
Lets connect on this when you are back.

**Comment by meskill** [comment]
Do we really need to capture the output separately?

Consider this:
- instead of calling some function from the lib we can start the binary programmatically and capture it's output.
- also we can use different tracing crates to capture the output for testing, but I don't think making changes to the code to test the cli output is a good approach

**Comment by ssddOnTop** [comment]
>     * instead of calling some function from the lib we can start the binary programmatically and capture it's output.

but is that a good approach?

we couldn't get codecov, if something throws an runtime error, we won't have much information about that.. etc

**Comment by meskill** [comment]
> > ```
> > * instead of calling some function from the lib we can start the binary programmatically and capture it's output.
> > ```
> 
> but is that a good approach?
> 
> we couldn't get codecov, if something throws an runtime error, we won't have much information about that.. etc

I believe it'd better represent end user experience and we will test the actual output instead of testing that some data has been written somewhere that won't mean the actual output (for testing TAILCALL_LOG). 
Also, code coverage is possible for standalone binaries though it's probably not that easy to collect, agree

**Comment by ssddOnTop** [comment]
> I believe it'd better represent end user experience and we will test the actual output instead of testing that some data has been written somewhere that won't mean the actual output (for testing TAILCALL_LOG). Also, code coverage is possible for standalone binaries though it's probably not that easy to collect, agree

Okay.

Closing this PR and I'd raise new PR based on the suggestions.

**Comment by meskill** [comment]
> > I believe it'd better represent end user experience and we will test the actual output instead of testing that some data has been written somewhere that won't mean the actual output (for testing TAILCALL_LOG). Also, code coverage is possible for standalone binaries though it's probably not that easy to collect, agree
> 
> Okay.
> 
> Closing this PR and I'd raise new PR based on the suggestions.

Please discuss first with @tusharmath about the approach

**Pull request closed without merging**
