### PR TITLE
refactor: Rename cloudflare package

### LINKED ISSUE #1702: Refactor: Rename cloudflare
Rename `cloudflare` workspace to `tailcall-coudflare`.

### PR DESCRIPTION
**Pull request by webbdays**
**Summary:**  
rename

**Issue Reference(s):**  
Fixes #1702 

**Build & Testing:**

- [Yes] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [yes ] I have performed a self-review of my code.
- [Yes ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

**Review by tusharmath — APPROVED** [review]

**Comment by tusharmath** [comment]
@webbdays Thanks! We need something similar with `aws-lambda` also :) Do you mind creating a PR with those changes also?

**Comment by webbdays** [comment]
sure.

**Comment by webbdays** [comment]
tailcall-awa-lambda ?

**Comment by tusharmath** [comment]
Yes.

**Pull request merged**
