### PR TITLE
feat: Resolve startup issue with Tailcall using benchmark.graphql

### PR DESCRIPTION
**Pull request by feliciien**
Fixed an issue where Tailcall was encountering an error when attempting to start the server using the benchmark.graphql file. The issue was resolved by providing the correct Server Configuration:

The first schema sets enableQueryValidation: false in the @server directive, while the second schema sets enableResponseValidation: true. This potentially changes how the server handles validation.
The second schema has additional comments specifying the server and base URL configurations.
Changes Made:
- Corrected file path in Cargo commands for check and start operations.
- Successfully launched Tailcall server without errors using benchmark.graphql.

Resolves: /claim #667

**Summary:**  
Fixed an issue where Tailcall was encountering a "No such file or directory" error when attempting to start the server using the benchmark.graphql file. The issue was resolved by providing the correct file path and ensuring its accessibility.

Changes Made:
- Corrected file path in Cargo commands for check and start operations.
- Successfully launched Tailcall server without errors using benchmark.graphql.

**Issue Reference(s):**  
Fixes #... _
**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` 
- [x] I have run `cargo run -- start [file-path] -> Server  start`.

**Checklist:**
- [x] I have performed a self-review of my code.

### CODE REVIEW

**Comment by feliciien** [comment]
Screenshot 2023-11-21 at 8 32 50 AM

**Comment by feliciien** [comment]
Screenshot 2023-11-21 at 8 47 47 AM

**Comment by feliciien** [comment]
Just wanted to let you know that I've made the necessary updates based on the previous review feedback. Removed 'Que' type definition and adjusted the benchmark.graphql schema to fix the 'Type "Que" not found' issue. The server now runs smoothly. Please review

**Comment by amitksingh1490** [comment]
@feliciien Thanks for opening the PR, but this is not solving the problem which is described in the issue. #667

**Pull request closed without merging**
