### PR TITLE
CI : made format,clippy,test run in parallel

### PR DESCRIPTION
**Pull request by akansh-bansal**
made format,clippy,test run in parallel

Fixes: #394
/claim: #394

Build & Testing:

 I ran cargo test successfully.
Checklist:

 I have performed a self-review of my own code.

### CODE REVIEW

**Comment by tusharmath** [comment]
@akansh-bansal I think you have merged two separate PRs in this one?

**Comment by tusharmath** [comment]
No build is running it seems on this PR.

**Comment by akansh-bansal** [comment]
> No build is running it seems on this PR.



> No build is running it seems on this PR.

i think test will build by default not sure though, i can add build if you want

**Comment by tusharmath** [comment]
The build was running until https://github.com/tailcallhq/tailcall/pull/405/commits/5796d09a27ef5ef0821c1fd635a79f557025a074

But now it's not running.

**Comment by tusharmath** [comment]
Fixed in #396

**Pull request closed without merging**
