### PR TITLE
feat: Windows builds in CI

### PR DESCRIPTION
**Pull request by Dhanus3133**
Added the following Windows CPU architectures

- x86_64-pc-windows-msvc
- x86_64-pc-windows-gnu
- aarch64-pc-windows-msvc
- aarch64-pc-windows-gnu
- i686-pc-windows-gnu

/claim #498

### CODE REVIEW

**Comment by tusharmath** [comment]
@amitksingh1490 Can you look at this?

**Comment by amitksingh1490** [comment]
image
Failing with this
Please check logs here for ref
https://github.com/tailcallhq/tailcall/pull/582

**Comment by Dhanus3133** [comment]
@amitksingh1490 can you kindly try it again. Thanks

**Comment by amitksingh1490** [comment]
please make PR against this branch test/windows-build
https://github.com/tailcallhq/tailcall/pull/582
I will merge that and test
also here `fix: removed windows aarch64` support for aarch64, we shouldn't do that, Ideally we should use cross or install correct toolchain

**Comment by amitksingh1490** [comment]
@tusharmath Please reward bounty for this PR to @Dhanus3133 , because I have copied code from here as we needed windows build urgently.

**Comment by tusharmath** [comment]
Trying with /approve

**Pull request closed without merging**
