### PR TITLE
refactor: make from_config.rs modular

### PR DESCRIPTION
**Pull request by 0x61nas**
**Summary:**  
 Split from_config into smaller module with separate files for easier maintenance.

**Issue Reference(s):**  
- Closes: #384

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh` to address and fix linting issues.

**Checklist:**

- [x] I have added relevant unit & integration tests.
- [x] I have updated the documentation accordingly (if applicable).
- [x] I have performed a self-review of my own code.

/claim #384

### CODE REVIEW

**Comment by tusharmath** [comment]
@0x61nas This is great! We just need to create files for each operator like mentioned in the issue.

**Comment by 0x61nas** [comment]
did we need to use `Transform` with all of them too?

**Comment by tusharmath** [comment]
@0x61nas Yes, that's the idea. Happy to discuss if you think there is a better way.

**Comment by 0x61nas** [comment]
I have encountered a test failure in the client-side (`test_failures_in_client_sdl`), and I will work diligently to rectify it. I sincerely hope that you will have the opportunity to review the changes during this time.

**Comment by tusharmath** [comment]
Absolutely. Feel free to connect on discord channel if you need something
urgent

**Comment by 0x61nas** [comment]
Is there any plan to review this @tusharmath ?, I know that it's total mess probably, but I just need to some feedback to know if I was on the right path or no.

**Comment by tusharmath** [comment]
@0x61nas Thanks! Apologies for missing this. It's a large PR 🙈

**Comment by tusharmath** [comment]
@0x61nas Can you give me access to commit in your fork? And resolve the conflict one last time 🙏

**Comment by 0x61nas** [comment]
> @0x61nas Can you give me access to commit in your fork?

I did send an invitation to you; https://github.com/anas-contribs/tailcall/invitations

> And resolve the conflict one last time 🙏
Ok, I'll solve it son as I can

**Comment by tusharmath** [comment]
The implementation of Transform wasn't good enough for us to compose. I implemented, `TryFold` that is kind of like Transform, but composes much better. The changes required are as follows — 


- [ ] impl TryFolding instead of Transform
- [ ] Compose all TryFolding using `TryFold::try_all`

**Comment by 0x61nas** [comment]
> The implementation of Transform wasn't good enough for us to compose.

I wanted to say that from a while XD, it doesn't make sense for some operations and I found myself do things I really didn't wanna do because it's expensive, but I didn't find any other option in my head

> I implemented, `TryFold` that is kind of like Transform, but composes much better. The changes required are as follows —
> 
>     * [ ]  impl TryFolding instead of Transform
> 
>     * [ ]  Compose all TryFolding using `TryFold::try_all`

I'll work on this

**Comment by tusharmath** [comment]
@0x61nas I think of all the PRs I am really looking forward to this one. This is a constant source of conflicts and chaos in the repo.

**Comment by 0x61nas** [comment]
> @0x61nas I think of all the PRs I am really looking forward to this one. This is a constant source of conflicts and chaos in the repo.

Sorry for this, I also want to get this merged, I'll try to get it done as fast as I can

**Comment by 0x61nas** [comment]
@tusharmath sorry, but I need some help here. I can't get this o work

```rust
pub fn config_blueprint(config: &Config) -> Valid<Blueprint> {
  let blueprint = TryFold::try_all::<TryFold<Config, Blueprint, String>>(vec![
    SchemaFold,
    DefinitionsFold,
    DirectiveFold,
    ServerFold,
  ])
  .try_fold(config, Blueprint::default())?;
  Ok(compress::compress(blueprint))
}
```
cause those are def rent types, and I tried to bind them to `dyn TryFolding<Input = Config, Value = Blueprint, Error = String>` but it didn't work to because the `Collet` struct require the items to be sized

**Comment by tusharmath** [comment]
@0x61nas did u see my message above? I have highlighted the exact point.

**Comment by 0x61nas** [comment]
> @0x61nas did u see my message [above](https://github.com/tailcallhq/tailcall/pull/445#discussion_r1362241485)? I have highlighted the exact point.

yeh I see, but I didn't get it apparently, how the default `try_fold` should look like. In this time it is different for each type

**Pull request closed without merging**
