### PR TITLE
Refactor/prettier ci

### LINKED ISSUE #409: Integrate Prettier on CI
**Problem**
GraphQL, YAML and JSON files remain unformatted formatted inconsistently

**Solution**

Integrate [prettier](https://prettier.io/) on the CI as a lint check to make sure all the .graphql files and yaml and json files are consistently formatted.

### PR DESCRIPTION
**Pull request by mahmoudfarouq**
/claim #409

closes #409

### CODE REVIEW

**Comment by tusharmath** [comment]
Can you check why the build is failing? I think the action isn't correctly setup.

**Comment by mahmoudfarouq** [comment]
Hi @tusharmath , It's fixed now and runs on my [PR](https://github.com/mahmoudfarouq/tailcall/pull/1), please approve the run on this one.

**Comment by mahmoudfarouq** [comment]
The failing tests fail because of white space differences between the generated code and the expected(which is now formatted), how do you think we can tackle this?

**Comment by tusharmath** [comment]
@mahmoudfarouq Thanks for your PR!

Need to identify where is that whitespace coming from and that if we can trim in our Rust code or use a different config for prettier to make this work.

**Comment by amitksingh1490** [comment]
We've decided to proceed with #410, but truly appreciate your input and effort. Thank you for your contribution. 🙏🏽

**Pull request closed without merging**
